export const products = [
  {
    _id: "001",
    name: "Men Checked Shirt",
    img: "https://rukminim1.flixcart.com/image/880/1056/kwtkxow0/shirt/c/u/n/xl-brd-white-p-v-creations-original-imag9f3yxz7d89t4.jpeg?q=50",
    alt: "mens shirt",
    brand: "Roadster",
    newPrice: 1750,
    oldPrice: 2499,
    discount: 67,
    size: "L",
    idealFor: "M",
    rating: 4.2,
  },
  {
    _id: "002",
    name: "Women Crop Top",
    img: "https://rukminim1.flixcart.com/image/880/1056/krf91u80/top/g/n/v/xs-lbt-13-maroon-london-belly-original-imag57qgzcm3hsmv.jpeg?q=50",
    alt: "womens top",
    brand: "Forever 21",
    newPrice: 750,
    oldPrice: 1499,
    discount: 75,
    size: "M",
    idealFor: "W",
    rating: 4.5,
  },
  {
    _id: "003",
    name: "Women Solid Shirt",
    img: "https://rukminim1.flixcart.com/image/880/1056/kf2v3ww0/top/z/f/t/l-044-yukon01-original-imafvhkejzfhqaqz.jpeg?q=50",
    alt: "Women shirt",
    brand: "Zara",
    newPrice: 2750,
    oldPrice: 3499,
    discount: 46,
    size: "L",
    idealFor: "W",
    rating: 3.9,
  },
  {
    _id: "004",
    name: "Men Solid Shirt",
    brand: "Peter England",
    img: "https://rukminim1.flixcart.com/image/580/696/kwzap3k0/shirt/r/q/j/l-lstr-acqua-p-v-creations-original-imag9jggj6naa4cu.jpeg?q=50",
    alt: "mens shirt",
    newPrice: 2554,
    oldPrice: 3499,
    discount: 27,
    size: "XL",
    idealFor: "M",
    rating: 3.5,
  },
  {
    _id: "005",
    name: "Men Solid T-Shirt",
    brand: "Roadster",
    img: "https://rukminim1.flixcart.com/image/580/696/kz8qsnk0/t-shirt/g/z/n/m-db1024-42-3bros-original-imagbawh38j3ghzr.jpeg?q=50",
    alt: "mens t-shirt",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 21,
    size: "M",
    idealFor: "M",
    rating: 3.2,
  },
  {
    _id: "006",
    name: "Women Printed Top",
    img: "https://rukminim1.flixcart.com/image/580/696/kzhbfrk0/top/v/b/6/m-fancy-top-shree-villa-original-imagbhgpqkj9snta.jpeg?q=50",
    alt: "Women Printed Top",
    brand: "Zara",
    newPrice: 1750,
    oldPrice: 2499,
    discount: 27,
    size: "S",
    idealFor: "W",
    rating: 3.2,
  },
  {
    _id: "007",
    name: "Men Regular V Neck T-Shirt",
    img: "https://rukminim1.flixcart.com/image/580/696/k6gsk280/t-shirt/e/z/h/xl-pp-374-385-379-revesto-original-imafkxwnetcxt4xr.jpeg?q=50",
    alt: "mens t-shirt",
    brand: "DNMX",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 90,
    size: "XXL",
    idealFor: "M",
    rating: 2.2,
  },
  {
    _id: "008",
    name: "Women Regular Top",
    img: "https://rukminim1.flixcart.com/image/580/696/knni7ww0/top/o/m/o/s-dmp303-dmp-fashion-original-imag2a5qkjgjf22k.jpeg?q=50",
    alt: "Women Regular Top",
    brand: "Forever 21",
    newPrice: 2750,
    oldPrice: 3499,
    discount: 44,
    size: "XXL",
    idealFor: "W",
    rating: 2.2,
  },
  {
    _id: "009",
    name: "Women Solid T-Shirt",
    img: "https://rukminim1.flixcart.com/image/580/696/jzn0tjk0/t-shirt/t/y/g/s-fw-014-mrrd-s-first-wave-original-imaf2nxuqatamwhm.jpeg?q=50",
    alt: "Women t-shirt",
    brand: "Forever 21",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 39,
    size: "S",
    idealFor: "W",
    rating: 2.2,
  },
];
